### ISSUE TITLE
Expectations cljs (v2.1.0): Unable to resolve classname: js/Error

### ISSUE THREAD

**Issue by ptaoussanis** [jaycfields/expectations#54]
Hi @imikushin, just noticed something interesting while debugging the macro issue.

With the same [encore](https://github.com/ptaoussanis/encore) repo, using Cljs 0.0-2985:

Running `lein clean; lein cljx once; lein cljsbuild once main` works fine (Cljs is compiled, w/o problems).
Running `lein clean; lein cljx once; lein cljsbuild once tests` works fine (Cljs is compiled, w/o problems).
Running `lein clean; lein cljx once; lein cljsbuild once` produces an error:
```
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/ptaoussanis/Projects/encore/target/tests.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Reloading Clojure file "/taoensso/encore/tests.clj" failed.
clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException: Unable to resolve classname: js/Error, compiling:(taoensso/encore/tests.clj:34:1)
             Compiler.java:6716 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6461 clojure.lang.Compiler.analyze
             Compiler.java:5837 clojure.lang.Compiler$BodyExpr$Parser.parse
             Compiler.java:5272 clojure.lang.Compiler$FnMethod.parse
             Compiler.java:3901 clojure.lang.Compiler$FnExpr.parse
             Compiler.java:6707 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6461 clojure.lang.Compiler.analyze
             Compiler.java:3713 clojure.lang.Compiler$InvokeExpr.parse
             Compiler.java:6711 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6461 clojure.lang.Compiler.analyze
             Compiler.java:2210 clojure.lang.Compiler$TryExpr$Parser.parse
             Compiler.java:6709 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
               Compiler.java:38 clojure.lang.Compiler.access$200
             Compiler.java:6105 clojure.lang.Compiler$LetExpr$Parser.parse
             Compiler.java:6709 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6697 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6697 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6461 clojure.lang.Compiler.analyze
             Compiler.java:5837 clojure.lang.Compiler$BodyExpr$Parser.parse
             Compiler.java:5272 clojure.lang.Compiler$FnMethod.parse
             Compiler.java:3901 clojure.lang.Compiler$FnExpr.parse
             Compiler.java:6707 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6697 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
               Compiler.java:38 clojure.lang.Compiler.access$200
              Compiler.java:560 clojure.lang.Compiler$DefExpr$Parser.parse
             Compiler.java:6709 clojure.lang.Compiler.analyzeSeq
             Compiler.java:6500 clojure.lang.Compiler.analyze
             Compiler.java:6461 clojure.lang.Compiler.analyze
             Compiler.java:6772 clojure.lang.Compiler.eval
             Compiler.java:7195 clojure.lang.Compiler.load
                    RT.java:370 clojure.lang.RT.loadResourceScript
                    RT.java:361 clojure.lang.RT.loadResourceScript
                    RT.java:440 clojure.lang.RT.load
                    RT.java:411 clojure.lang.RT.load
                  core.clj:5808 clojure.core/load[fn]
                  core.clj:5807 clojure.core/load
                RestFn.java:408 clojure.lang.RestFn.invoke
               compiler.clj:129 cljsbuild.compiler/reload-clojure[fn]
               compiler.clj:128 cljsbuild.compiler/reload-clojure
               compiler.clj:176 cljsbuild.compiler/run-compiler
form-init1797310464061109205.clj:1 user/eval3747[fn]
form-init1797310464061109205.clj:1 user/eval3747[fn]
                LazySeq.java:40 clojure.lang.LazySeq.sval
                LazySeq.java:49 clojure.lang.LazySeq.seq
                   Cons.java:39 clojure.lang.Cons.next
                LazySeq.java:81 clojure.lang.LazySeq.next
                    RT.java:644 clojure.lang.RT.next
                    core.clj:64 clojure.core/next
                  core.clj:3005 clojure.core/dorun
                  core.clj:3020 clojure.core/doall
form-init1797310464061109205.clj:1 user/eval3747
             Compiler.java:6768 clojure.lang.Compiler.eval
             Compiler.java:6758 clojure.lang.Compiler.eval
             Compiler.java:7195 clojure.lang.Compiler.load
             Compiler.java:7151 clojure.lang.Compiler.loadFile
                   main.clj:274 clojure.main/load-script
                   main.clj:279 clojure.main/init-opt
                   main.clj:307 clojure.main/initialize
                   main.clj:342 clojure.main/null-opt
                   main.clj:420 clojure.main/main
                RestFn.java:421 clojure.lang.RestFn.invoke
                   Var.java:383 clojure.lang.Var.invoke
                   AFn.java:156 clojure.lang.AFn.applyToHelper
                   Var.java:700 clojure.lang.Var.applyTo
                   main.java:37 clojure.main.main
Caused by: java.lang.IllegalArgumentException: Unable to resolve classname: js/Error
             Compiler.java:2247 clojure.lang.Compiler$TryExpr$Parser.parse
             Compiler.java:6709 clojure.lang.Compiler.analyzeSeq
```

Encore's project.clj :cljsbuild section has the "main" and "tests" profiles configured to compile **in parallel** when `lein cljsbuild once` is called without a specific profile name:
```clojure
   :builds
   [{:id "main"
     :source-paths   ["src" "target/classes"]
     ;; :notify-command ["terminal-notifier" "-title" "cljsbuild" "-m"]
     :compiler       {:output-to "target/main.js"
                      :optimizations :advanced
                      :pretty-print false}}
    {:id "tests"
     :source-paths   ["src" "target/classes" "test" "target/test-classes"]
     :notify-command ["node" "target/tests.js"]
     :compiler       {:output-to "target/tests.js"
                      :optimizations :simple ; Necessary for node.js
                      :pretty-print true
                      :target :nodejs
                      :hashbang false ; Ref. http://goo.gl/vrtNDR
                      :main "taoensso.encore.tests"}}]
```

So it seems that this error occurs only for **parallel builds**.

From what I can tell, the offender is `expectations.platform/err-type`:
```clojure
(defn err-type [] (if (cljs?) `~'js/Error `Throwable))
```

Looks like it might be some kind of race condition against `(defn cljs? [] (boolean (find-ns 'cljs.core)))`?

This isn't an important or urgent issue (it's easy to work around), just reporting it in case you weren't aware.

Cheers! :-)

**Comment by imikushin** [comment]
Thanks, Peter. ClojureScript continues to amuze :) I'll definitely take a
look.

**Comment by jaycfields** [comment]
@imikushin & @ptaoussanis 

Is this still an issue or can I close?

(doing a little spring-cleaning today)

**Comment by ptaoussanis** [comment]
Hi @jaycfields, still an issue with 2.1.0 I believe - not sure if there've been any releases since then that resolve this though?

**Comment by jaycfields** [comment]
thanks @ptaoussanis 

I'll have to leave it for our cljs expert, @imikushin, but good to know it's still an open issue.

**Comment by plexus** [comment]
The problem is this part

``` clojure
(defn cljs? []
  (boolean (find-ns 'cljs.core)))
```

This means that as soon as ClojureScript is loaded (e.g. you're running a clj+cljs project with Figwheel), then all tests will be assumed to be ClojureScript.

I'm not sure I'm understanding yet 100% the subtleties here, but it seems because macros are expanded by Clojure you can't rely on cljc/cljx reader conditionals.

**Comment by plexus** [comment]
It seems at least during macroexpansion you can check the magic variable `&env`, as is done here 

https://github.com/plumatic/schema/blob/master/src/clj/schema/macros.clj#L10-L19

```clojure
(defn cljs-env?
  "Take the &env from a macro, and tell whether we are expanding into cljs."
  [env]
  (boolean (:ns env)))

(defmacro if-cljs
  "Return then if we are generating cljs code and else for Clojure code.
   https://groups.google.com/d/msg/clojurescript/iBY5HaQda4A/w1lAQi9_AwsJ"
  [then else]
  (if (cljs-env? &env) then else))
```
